### ISSUE TITLE
Sidekiq 4

### ISSUE THREAD

**Issue by jnylen** [kevinbuch/sidekiq_schedulable#1]
Hi Kevin,
I'm using this for Sidekiq 3 instead of Sidetiq.

Are you going to look into getting this moved to Sidekiq 4 in the upcoming months?

**Comment by kevbuchanan** [comment]
Hi Joakim,
I've updated the gemspec to allow for Sidekiq 4 and published v0.1.0, which should be all that's required. Let me know if you find any issues with the upgrade.
